[profile.default]
solc = "0.8.17"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "src/=src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
]

[fmt]
line_length = 79
tab_width = 2
number_underscore = "thousands"
wrap_comments = true